name: cancelable_future
description: Exploring the possibility of adding a cancelable future.
version: 0.2.1
repository: https://github.com/vi-k/cancelable_future

environment:
  sdk: ^3.2.5

dependencies:
  meta: ^1.12.0

dev_dependencies:
  lints: ^3.0.0
  stack_trace: ^1.11.1
  test: ^1.24.0
  vm_service: ^14.0.0
