name: cancelable_future
description: Exploring the possibility of adding a cancelable future.
version: 0.4.0
repository: https://github.com/vi-k/cancelable_future

environment:
  sdk: ^3.7.0

dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  vm_service: ^15.0.0
