name: cancelable_future
description: This package academically provides an opportunity to cancel the future.
version: 0.4.3
repository: https://github.com/vi-k/cancelable_future

topics:
- future
- cancelable-future
- async

environment:
  sdk: ^3.9.2

dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.15
  vm_service: ^15.0.0
